services:
  web:
    image: php:apache
    container_name: generador_php
    ports:
      - "8030:80"
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    container_name: generador_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_reportes
      MYSQL_USER: email
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"